name: Build Program

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Rust toolchain specified in rust-toolchain file
        shell: bash
        run: rustup show

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: build rust
        run: cargo build

      - name: Build SP1 program
        run: |
          cd program
          ~/.sp1/bin/cargo-prove prove build
